[pytest]
# Logları konsolda göster
log_cli = true
# Sadece INFO ve üzerini göster (DEBUG, INFO, WARNING, ERROR)
log_cli_level = INFO
# Logların başında saat ve hangi dosyadan geldiği yazsın
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S